[MODINVOICE-275] Invoice poNumbers needs to be updated when an invoice line is deleted
folio-org/mod-invoice pull request #281
Opened 2021-08-12 07:11 UTC by aleksandr2110

## Purpose

## Approach

#### TODOS and Open Questions

## Learning

## Pre-Merge Checklist:
Before merging this PR, please go through the following list and take appropriate actions.

- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] Were any API paths or methods changed, added or removed?
  - [ ] Were there any schema changes?
  - [ ] Did any of the interface versions change?
  - [ ] Were permissions changed, added, or removed?
  - [ ] Are there new interface dependencies?
  - [ ] There are no breaking changes in this PR.
  
If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?  
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2021-08-12 10:55 UTC, AndreiMPV requested changes

2021-08-12 10:55 UTC, AndreiMPV commented on src/main/java/org/folio/rest/util/InvoiceHolder.java
> +package org.folio.rest.util;
Please put under package org.folio.models

2021-08-17 10:38 UTC, MaksymShtanko approved these changes

2021-08-17 10:42 UTC, grabsefx commented on src/main/java/org/folio/rest/impl/InvoiceLineHelper.java
> +      .thenCompose(poLine -> orderService.getOrder(poLine.getPurchaseOrderId(), requestContext))
please use cross-index query for retreiving order by polineId in a single request
`"/orders/composite-orders?query=poLine.id = {{id}}"`

2021-08-17 13:18 UTC, grabsefx approved these changes

2021-08-17 13:25 UTC, aleksandr2110 commented on src/main/java/org/folio/rest/util/InvoiceHolder.java
> +package org.folio.rest.util;
Done

2021-08-17 13:50 UTC, aleksandr2110 reviewed
fixed

2021-08-17 14:11 UTC, AndreiMPV approved these changes

2021-08-17 14:12 UTC, merged