MODINVOICE-290 - Release old POL encumbrances even if invoice line has changed funds
folio-org/mod-invoice pull request #286
Opened 2021-09-01 14:15 UTC by mogrim

## Purpose
Fix a problem with encumbrances not being released for POL if invoice line created for that POL was edited to use different funds even if invoice that is being approved is set to release encumbrances.

## Approach
- When approving invoice search every POL for encumbrances that don't have same fund ID and POL ID as any of encumbrances in the invoice lines.
- Release such encumbrances.

## Pre-Merge Checklist:
Before merging this PR, please go through the following list and take appropriate actions.

- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] Were any API paths or methods changed, added or removed?
  - [ ] Were there any schema changes?
  - [ ] Did any of the interface versions change?
  - [ ] Were permissions changed, added, or removed?
  - [ ] Are there new interface dependencies?
  - [ ] There are no breaking changes in this PR.
  
If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?  
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2021-09-01 15:42 UTC, AndreiMPV requested changes

2021-09-01 15:42 UTC, AndreiMPV commented on src/main/java/org/folio/services/finance/transaction/PendingPaymentWorkflowService.java
> +        baseTransactionService.releaseEncumbrance(transaction, requestContext);
It should be in scope of async flow cleanupOldEncumbrances(...). In your case control will be returned immediately and if release failed no way to understand that

2021-09-02 11:00 UTC, AndreiMPV approved these changes

2021-09-02 12:21 UTC, grabsefx approved these changes

2021-09-02 12:29 UTC, merged